project:
  type: website
  output-dir: docs
  resources:
    - templates/*.qmd
    - followon/*.qmd
    - downloads/
    - assets/images/
  render:
    - "**/*.qmd"
    - "!templates/"
    - "!followon/"
    - "!**/*-notebook.qmd"
    - "!downloads/"

website:
  title: "GoldPsychR"
  description: "R for Psychology at Goldsmiths"
  
  navbar:
    logo: assets/images/svg/goldpsychr-logo-animated.svg
    title: false
    background: "#9B1B30"
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Labs"
        href: labs/index.qmd
      - text: "R Toolbox"
        href: toolbox/index.qmd
      # - text: "Pedagogical Approach"
      #   href: pedagogical.qmd
    right:
      - icon: github
        href: https://github.com/LittleMonkeyLab/GoldPsychR
      - text: "RStudio Server"
        href: https://psy909.gold.ac.uk/rstudioserver/

  sidebar:
    # logo: assets/images/GoldLogo.png
    # header: "**GoldPsychR**"
    # tools:
    #   - icon: github
    #     menu:
    #       - text: Source Code
    #         href: https://github.com/LittleMonkeyLab/GoldPsychR
    #       - text: Data Repository
    #         href: https://github.com/LittleMonkeyLab/datarepo
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: labs/index.qmd
        text: Labs Overview
      
      - text: "---"
      
      - section: "Lab 1: Intro & Descriptives"
        contents:
          - text: "Lab Materials"
            href: labs/lab01.qmd
          # - text: "Slides"
          #   href: slides/lab1-slides.qmd
          # - text: "WebR Practice"
          #   href: chapters/lab1-webr.qmd
          # - text: "Follow-On: Wellbeing Study"
          #   href: followon/lab1-followon.qmd
          # - text: "Exercise Template"
          #   href: templates/lab1-exercise.qmd

      - section: "Lab 2: T-Tests"
        contents:
          - text: "Lab Materials"
            href: labs/lab02.qmd

      - section: "Lab 3: ANOVA"
        contents:
          - text: "Lab Materials"
            href: labs/lab03.qmd

      - section: "Lab 4: Correlation & Regression"
        contents:
          - text: "Lab Materials"
            href: labs/lab04.qmd

      - text: "---"
      
      - section: "R Toolbox"
        contents:
          - text: "Toolbox Home"
            href: toolbox/index.qmd
          - text: "R Handbook (Single Page)"
            href: r-handbook.qmd

      - section: "Boil in the Bag"
        contents:
          - text: "All Templates"
            href: boil_in_the_bag/00_index.qmd
          - text: "Independent T-Test"
            href: boil_in_the_bag/01_independent_ttest.qmd
          - text: "Paired T-Test"
            href: boil_in_the_bag/02_paired_ttest.qmd
          - text: "One-Way ANOVA"
            href: boil_in_the_bag/03_oneway_anova.qmd
          - text: "Factorial ANOVA"
            href: boil_in_the_bag/04_factorial_anova.qmd
          - text: "Repeated Measures ANOVA"
            href: boil_in_the_bag/05_repeated_measures_anova.qmd
          - text: "Mixed ANOVA"
            href: boil_in_the_bag/06_mixed_anova.qmd
          - text: "Simple Regression"
            href: boil_in_the_bag/07_simple_regression.qmd
          - text: "Multiple Regression (2 pred)"
            href: boil_in_the_bag/08_multiple_regression_2pred.qmd
          - text: "Multiple Regression (3 pred)"
            href: boil_in_the_bag/09_multiple_regression_3pred.qmd
          # - text: "Setup & Installation"
          #   href: toolbox/setup.qmd
          # - text: "Importing Data"
          #   href: toolbox/import.qmd
          # - text: "Data Wrangling"
          #   href: toolbox/wrangle.qmd
          # - text: "Plots & Visualisation"
          #   href: toolbox/plots.qmd
          # - text: "Statistical Tests"
          #   href: toolbox/tests.qmd
          # - text: "Linear Models"
          #   href: toolbox/models.qmd
          # - text: "Reporting Results"
          #   href: toolbox/reporting.qmd
          # - text: "Troubleshooting"
          #   href: toolbox/troubleshooting.qmd
      
      - text: "---"
      
      # - href: pedagogical.qmd
      #   text: Pedagogical Approach
      # - href: followon/index.qmd
      #   text: About Follow-Ons

  page-footer:
    left: |
      Â© 2026 Goldsmiths, University of London
    center: |
      Made with ðŸ’› using [R](https://posit.co/products/open-source/rstudio/?sid=1) and [Quarto](https://quarto.org)
    right: |
      A LittleMonkeyLab caper | [Report an issue](https://github.com/LittleMonkeyLab/GoldPsychR/issues)

format:
  html:
    theme:
      light: [cosmo, assets/css/custom.scss]
    css:
      - include/webex.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-link: false
    code-tools: true
    highlight-style: github
    anchor-sections: true
    smooth-scroll: true
    scrollable: true
    include-after-body:
      - include/webex.js

filters:
  - webr

webr:
  packages: ['tidyverse']
  autoload-packages: false
  show-startup-message: false
  channel-type: "automatic"

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

author: "Gordon Wright"
date-modified: last-modified